version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      ConnectionStrings__Sql: Host=postgres;Port=5432;Database=workforce;Username=workforce;Password=workforce
      Mongo__ConnectionString: mongodb://mongo:27017
      Mongo__Database: workforce
      Rabbit__HostName: rabbitmq
      Rabbit__Port: 5672
      Rabbit__UserName: guest
      Rabbit__Password: guest
      Rabbit__VirtualHost: /
      Rabbit__ExchangePrefix: workforce.events
      Rabbit__AuditQueueName: workforce.audit
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - mongo
      - rabbitmq

  audit-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.auditworker
    environment:
      Mongo__ConnectionString: mongodb://mongo:27017
      Mongo__Database: workforce
      Rabbit__HostName: rabbitmq
      Rabbit__Port: 5672
      Rabbit__UserName: guest
      Rabbit__Password: guest
      Rabbit__VirtualHost: /
      Rabbit__ExchangePrefix: workforce.events
      Rabbit__AuditQueueName: workforce.audit
    depends_on:
      - mongo
      - rabbitmq

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: workforce
      POSTGRES_PASSWORD: workforce
      POSTGRES_DB: workforce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data:
  mongo_data:
